language: cpp
sudo: required
dist: xenial

# osx_image: xcode11.3
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
services:
  - mysql
install:
  - sudo apt-get install libmysqlclient-dev -y
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/mysql
  - sudo ldconfig
before_script:
  - sudo mysql -e 'CREATE DATABASE mysql_c_test;'
  - sudo mysql -e 'CREATE DATABASE odb_test;'
#  - mysql --user=travis --database=odb_test < person.sql
  - ls
  - pwd
addons:
  apt:
    update: true

env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERSEBOSE=1
  - ls
  - ./mysqlcapiinlinux