language: cpp
sudo: required
dist: xenial

# osx_image: xcode11.3
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
install:
before_script:
  - ls
  - pwd
addons:
  apt:
    update: true

env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERSEBOSE=1
  - ls